# environment.yml
name: tts-api-env  # Name of the environment
channels:
  - conda-forge  # Reliable channel for packages
  - defaults
dependencies:
  - python=3.9  # Specify Python version
  - flask  # Install Flask via Conda
  - pydub  # Install pydub via Conda
  - cachetools  # Install cachetools via Conda
  - pip  # Include pip for packages not available in Conda
  - kokoro>=0.9.4
  - libstdcxx~=12.4.0 # Needed to load espeak correctly. Try removing this if you're facing issues with Espeak fallback.
  - pip:
      - numpy==1.23.5
      - scipy==1.9.3
      - transformers==4.30.2
      - soundfile
      - misaki[en]
      - piper-tts  # Install Piper TTS via pip
