# environment.yml
name: tts-api-env  # Name of the environment
channels:
  - conda-forge  # Reliable channel for packages
  - defaults
dependencies:
  - python=3.9  # Specify Python version
  - flask  # Install Flask via Conda
  - pydub  # Install pydub via Conda
  - pip  # Include pip for packages not available in Conda
  - pip:
      - piper-tts  # Install Piper TTS via pip
      - google-cloud-texttospeech  # Install Google Cloud TTS library via pip
      - google-cloud-speech
      - transformers
      - torch